### ISSUE TITLE
failed to build in MacOS and Ubuntu

### ISSUE THREAD

**Issue by jonirrings** [soarqin/3dsconv-c#1]
for MacOS c compiler is AppleClang 11.0.0.11000033
for Ubuntu c compiler is GNU 7.4.0

both indicate `unknown type name 'size_t'` and `implicit declaration of function 'fseeko64' is invalid in C99`

any solution ?

**Comment by soarqin** [comment]
commited a fix for linux, but no darwin env to test, please check if it works on darwin.

**Comment by jonirrings** [comment]
validated in win64 and darwin, the output files are matched with the same md5 sum.
nice work, bro.
I've ported a Rust version, but yours outperform much better with far less mem usage and binary size. :thumbsup:
